syntax = "proto3"

package uploadservice;

service UploadService {
    rpc UploadVideo(stream VideoChunk) returns (UploadResponse);
}

enum UploadStatus {
    UPLOAD_STATUS_UNSPECFIED = 0;

    ACCEPTED = 1;

    QUEUE_FULL = 2;

    DUPLICATE = 3;

    INVALID_FILE = 4;

    UPLOAD_ERROR = 5;
}

message UploadRequest {
    string filename = 1;

    int64 file_size = 2;

    string file_hash = 3;
}

message UploadPermission {
    bool allowed = 1;

    UploadStatus status = 2;

    string message = 3;
}

message VideoChunk {
    string upload_id = 1;

    string filename = 2;

    uint32 chunk_number = 3;

    bytes data = 4;

    bool is_last = 5;
}

message UploadResponse {
    UploadStatus status = 1;

    string message = 2;
}