syntax = "proto3";

package uploadservice;

service UploadService {
    rpc UploadVideo(stream VideoChunk) returns (UploadResponse);
    rpc CheckUploadCapacity(UploadRequest) returns (UploadPermission);
}

enum UploadStatus {
    UPLOAD_STATUS_UNSPECIFIED = 0;

    UPLOAD_STATUS_ACCEPTED = 1;

    UPLOAD_STATUS_QUEUE_FULL = 2;

    UPLOAD_STATUS_DUPLICATE = 3;

    UPLOAD_STATUS_INVALID_FILE = 4;

    UPLOAD_STATUS_UPLOAD_ERROR = 5;
}

message UploadRequest {
    string filename = 1;

    int64 file_size = 2;

    string file_hash = 3;

    string upload_id = 4;
}

message UploadPermission {
    bool allowed = 1;

    UploadStatus status = 2;

    string message = 3;
}

message VideoChunk {
    string upload_id = 1;

    string filename = 2;

    uint32 chunk_number = 3;

    bytes data = 4;

    bool is_last = 5;
}

message UploadResponse {
    UploadStatus status = 1;

    string message = 2;
}